### ISSUE TITLE
v 1.1 won't open for me

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [SunakazeKun/Captain-Toad-Save-editor#1]
I've tried double-clicking on the CTSe.jar icon and even tried the command line, and it won't open.

**Comment by SunakazeKun** [comment]
Make sure that the lib folder is in the same directory as the CTSe.jar file. Also, make sure you are running on newer Java versions. Does it print any errors when you run it through command line?

**Comment by dagreatbuzzsaw** [comment]
lib folder and CTS3.jar file is in the same directory, and my Java was updated.  I also have other Java programs on my desktop and they work fine.  As for the command line, this is what has come up:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/aurumsmods/ctse/CTSe has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by SunakazeKun** [comment]
No, your Java version is outdated. Your computer runs Java 8 (class file version 52) whereas it needs Java 17. Performing a proper Java update will fix compatibility.
